changed handler signature
petuum/pirlib pull request #14
Opened 2022-07-26 15:26 UTC by zhanyuanucb

Address https://github.com/petuum/pirlib/issues/12

2022-07-26 15:46 UTC, aurickq commented on pirlib/handlers/v1.py
> +        context: Dict[str, Any],
Why `dict` for event and context and not structured `dataclass`?

2022-07-28 06:27 UTC, zhanyuanucb commented on pirlib/handlers/v1.py
> +        context: Dict[str, Any],
`context` probably should be `TaskContext`
Do we also need to define a dataclass for event?

2022-07-28 20:44 UTC, aurickq commented on pirlib/handlers/v1.py
> +        context: Dict[str, Any],
Actually, the handler context probably should be different from the task context (task context is end-user-facing, while handler context is backend-developer-facing).
> Do we also need to define a dataclass for event?
I don't know for sure, that was my question. The difference is whether we want to specify a schema for event and context or not. My guess right now is that we do, because we'd want developers of different backends to use the same format for event and context.

2022-07-29 06:34 UTC, zhanyuanucb commented on pirlib/handlers/v1.py
> +        context: Dict[str, Any],
Yea I agree that handler context should be different from the task context. And let's specify their schema.

2022-08-03 00:22 UTC, zhanyuanucb commented on pirlib/handlers/v1.py
> +        context: Dict[str, Any],
updated

2022-08-03 21:50 UTC, aurickq requested changes

2022-08-03 21:50 UTC, aurickq commented on pirlib/handlers/v1.py
> +    node_config: Dict[str, Any]
Could maybe just put the entire `node` in here, since there are other useful information like the framework name and version

2022-08-03 21:50 UTC, aurickq commented on pirlib/handlers/v1.py
> +class HandlerContext(object):
`HandlerV1Context` to match `HandlerV1`? In the future we may have new versions of the handler that we want to support simultaneously.

2022-08-03 21:54 UTC, aurickq commented on pirlib/handlers/v1.py
> +class HandlerContext(object):
Same with `HandlerV1Event` below.

2022-08-03 23:21 UTC, zhanyuanucb commented on pirlib/handlers/v1.py
> +    node_config: Dict[str, Any]
If we put a `node` object here, then all backends will have some dependencies in pirlib when they construct `HandlerContext`. Is this fine?

2022-08-03 23:21 UTC, zhanyuanucb commented on pirlib/handlers/v1.py
> +class HandlerContext(object):
sounds good

2022-08-04 03:07 UTC, aurickq commented on pirlib/handlers/v1.py
> +    node_config: Dict[str, Any]
I think they already need to have a dependency on pirlib to construct the HandlerContext in the first place?

2022-08-04 05:52 UTC, zhanyuanucb commented on pirlib/handlers/v1.py
> +    node_config: Dict[str, Any]
I think that depends on how much we want pirlib and backend entangle with one another. 
For now, backend can get information like node config, framework and version from PIR.
Or we can import `node` and reconstruct a `node` instance from PIR

2022-08-04 14:30 UTC, aurickq commented on pirlib/handlers/v1.py
> +    node_config: Dict[str, Any]
So is the question whether we want the backend to need to pass the entire node along instead of just the config? If that's the question then I don't think it makes a huge difference, because (1) the backend needs to know the full node anyways since it needs to know the entrypoint, framework, inputs/outputs, etc. and (2) it needs to pass node.config to the handler because the user code needs it. The fact that (1) and (2) are true should mean it's possible for backends to simply pass along node instead of node.config.

2022-08-04 16:18 UTC, zhanyuanucb commented on pirlib/handlers/v1.py
> +    node_config: Dict[str, Any]
The backend can know the full node from PIR yaml or from node instance directly. So I think the difference is whether we want backend to pick the info (including config, framework, inputs/outputs) they need from PIR and put them in `HandlerContext`, or we simply pass a node instance.

2022-08-04 16:29 UTC, zhanyuanucb commented on pirlib/handlers/v1.py
> +    node_config: Dict[str, Any]
Oh wait... I realized that backend needs dependency in pirlib to run the `HandlerV1.run_handler` anyways. So it doesn't harm to just import `pirllib.pir.Node` and pass a node to `HandlerContext`

2022-08-04 19:56 UTC, aurickq approved these changes

2022-08-04 22:10 UTC, merged