Generate new PIR schema
petuum/pirlib pull request #2
Opened 2022-07-11 19:35 UTC by zhanyuanucb

Close EPF-191, EPF-194

- Generate PIR with new schema
  - The new schema is stored at: [here](https://github.com/zhanyuanucb/pirlib/blob/prototype/example/yaml/schema.yml)
- Reuse component (graphs, nodes, inputs, outputs) names as their IDs

2022-07-13 04:06 UTC, aurickq commented on pirlib/pir.py
> +    id: str
Doesn't the graph already contain a dict of nodes where the keys of that dict are the unique ids? Requiring this unique id to also be in the node itself seems like extra validation rules that are not needed, and a potential source of bugs.

Would be simpler and less error-prone to have a list of nodes where each node contains the unique id, or a dict of nodes where each node does not contain the unique id. Similar comment for all the other list to dict changes.

2022-07-13 04:06 UTC, aurickq commented on pirlib/pir.py
> +    dependencies: Optional[dict] = None
What's dependencies? Shouldn't the image already capture all dependencies?

2022-07-13 04:24 UTC, aurickq commented on pirlib/pir.py
> +    config: Dict[str, Any] = field(default_factory=dict)
What's the design goal here with the nested config dataclasses? Might be simpler to just have a single dict config for the node and let both the node's main code and the framework use the same dict as its config.

For example an AdaptDL config could simply be defined in node.config["adaptdl/num_nodes"].

2022-07-13 17:22 UTC, zhanyuanucb commented on example/yaml/schema.yml
> +# Copyright 2022 Petuum, Inc. All Rights Reserved.
I put it there temporarily so that people can refer to the expected schema. This file is in the format such that schema check can be done through yamale.
I'll probably remove it once the PIR schema validation tool is ready.

2022-07-13 17:23 UTC, zhanyuanucb commented on pirlib/pir.py
> +class GraphAnnotations:
agree

2022-07-13 17:56 UTC, zhanyuanucb commented on pirlib/pir.py
> +    dependencies: Optional[dict] = None
This `dependencies` is for Docker-free code packaging. For example, the environment exported by conda will be put into here.

2022-07-13 17:56 UTC, zhanyuanucb commented on pirlib/pir.py
> +    config: Dict[str, Any] = field(default_factory=dict)
agree

2022-07-13 19:11 UTC, zhanyuanucb commented on pirlib/pir.py
> +    id: str
that makes sense. I prefer list of components and each component contains its unique id

2022-07-13 19:12 UTC, zhanyuanucb commented on pirlib/pir.py
> +    dependencies: Optional[dict] = None
This `dependencies` is for Docker-free code packaging. For example, the environment exported by conda can be put into here

2022-07-13 19:40 UTC, aurickq commented on pirlib/pir.py
> +    dependencies: Optional[dict] = None
Can we make this addition when it's actually needed? Seems like it can be added in a backward-compatible way and this way we avoid dead code. We can just keep image as a child of node for now.

2022-07-15 19:19 UTC, aurickq commented on pirlib/pir.py
> +    id: str
Yeah IMO informational fields like human readable name should start out in annotations. It's easy later on to upgrade important fields to the schema if desired, but hard to remove if it starts out in the schema (breaks backward compatibility).

2022-07-15 19:37 UTC, aurickq commented on pirlib/pir.py
> +    id: str
Another idea is to make Metadata class for generic PIR components that has an optional name field and an optional annotations field. Then you can use this class in all the relevant entities.

Example:
```
class Metadata:
  name: Optional[str]
  annotations: Optional[dict]

class Node:
  ...
  meta: Metadata

class Graph:
  ...
  meta: Metadata
```

2022-07-15 22:29 UTC, aurickq commented on pirlib/pir.py
> -    framework: Optional[Framework] = None
Yeah, and we can have some convention like framework configs are `/`-separated:
```
node_config = {"num_epochs": 1, "adaptdl/num_nodes": 2}
@operator(config=node_config)
def train(inp):
    ...
```

2022-07-15 22:49 UTC, zhanyuanucb commented on pirlib/pir.py
> +    id: str
This generic Metadata sounds good to me.

2022-07-15 22:51 UTC, zhanyuanucb commented on pirlib/pir.py
> +class MetaData:
How about we make the MetaData class generic to PIR component, and then move the `iotype` to top-level field in `Input`, `Output`, `GraphInput`, and `GraphOutput`

2022-07-15 23:23 UTC, aurickq commented on pirlib/pir.py
> +class MetaData:
That sounds good to me but what about `schema`?

2022-07-15 23:33 UTC, zhanyuanucb commented on pirlib/pir.py
> +class MetaData:
`schema` can be an optional field in MetaData as well. But for now, it seems we don't have a use case to show it is necessary.

2022-07-15 23:51 UTC, aurickq commented on pirlib/pir.py
> +class MetaData:
Got it. In that case schema should probably be an annotation for now.

2022-07-16 00:09 UTC, zhanyuanucb commented
Sounds good

On Fri, Jul 15, 2022, 16:51 Aurick Qiao ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In pirlib/pir.py
> <https://github.com/petuum/pirlib/pull/2#discussion_r922581854>:
>
> > +    fields: List[MetaDataSchemaField] = field(default=list)
> +
> +    def __init__(
> +        self,
> +        type: Optional[str] = None,
> +        name: Optional[str] = None,
> +        fields: List[MetaDataSchemaField] = []
> +    ):
> +        self.type = type
> +        self.name = name
> +        self.fields = fields
> +        self.fields.append(MetaDataSchemaField())
> +
> +
> ***@***.***
> +class MetaData:
>
> Got it. In that case schema should probably be an annotation for now.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/petuum/pirlib/pull/2#discussion_r922581854>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHUES6RBOAWTM2T7VKFND63VUH2RNANCNFSM53IS4AVQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-07-18 19:37 UTC, aurickq requested changes

2022-07-18 19:37 UTC, aurickq commented on pirlib/pir.py
> +    codeurl: Optional[str] = None
Field order should match docstring

2022-07-18 19:37 UTC, aurickq commented on example/example.py
> +)
Don't need to change this public API. Internal logic can take care of translating `framework=AdaptDL(min_replicas=1, max_replicas=4)` into `config={"adaptdl/min_replicas": 1, "adaptdl/max_replicas": 4}`

2022-07-19 13:53 UTC, aurickq approved these changes

2022-07-19 15:41 UTC, merged