Implement cache api
petuum/pirlib pull request #27
Opened 2023-02-10 07:39 UTC by nikhilranjan7

2023-02-25 22:36 UTC, zhanyuanucb commented
@nikhilranjan7 @Nilabhra 
Some thoughts on cache key generation:
- Current implementation of `generate_cache_key` associates a cache key with file path and file content. Are we expecting given a file path, the file content will change? If so, in what scenario will that happen? What about letting the user make sure that given the file path, the file content won't change? Will that make the cache generation easier?

- It'll be better if there is a default way to generate the cache key since it is not natural that users *must* configure how to generate the cache key after they set `cache=True`. But it makes sense to expose the options so that users can customize their cache key generation if they really need it.
  - For example, if `cache=True`, then the cache key will be associated with the function signature and parameter values. But users can choose which parameter value to ignore.

2023-02-25 22:36 UTC, zhanyuanucb requested changes

2023-02-25 22:54 UTC, zhanyuanucb commented on examples/caching/ml_pipeline.py
> +@task(config=dict(cache=True, cache_key_file="hparams"))
You can refer how `framework` is merged into task/node config

2023-02-27 06:17 UTC, Nilabhra commented on pirlib/cache.py
> +def generate_cache_key(key_file: Path) -> str:
@zhanyuanucb True, can be easily fixed. @nikhilranjan7  can you update this part too when making the PR review changes?

2023-02-27 06:23 UTC, Nilabhra commented on examples/caching/ml_pipeline.py
> +@task(config=dict(cache=True, cache_key_file="hparams"))
@zhanyuanucb Thanks for pointing this out. We decided to use `config` because for caching, there needs to be two parameters, `cache` and `cache_key_file`, later, we might have `cache_key_dir`. The config dict allows us to encapsulate all of that. But your suggestion makes total sense and I would prefer to have it that way too. We will review this idea and see if we can push the modifications in this PR.

2023-02-27 07:40 UTC, Nilabhra commented
@zhanyuanucb 
>Current implementation of generate_cache_key associates a cache key with file path and file content. Are we expecting given a file path, the file content will change? If so, in what scenario will that happen? What about letting the user make sure that given the file path, the file content won't change? Will that make the cache generation easier?

Yes, the file contents are expected to change. Using TuunV2 as an example, the tuning algorithm can generate a set of parameters and write them to this file following a strict format. The tasks then uses these values to generate keys. Once the pipeline has finished executing, the tuning algorithm will generate a set of parameters yet again for the next run of the pipeline.

2023-02-27 07:41 UTC, Nilabhra commented
@zhanyuanucb 
>It'll be better if there is a default way to generate the cache key since it is not natural that users must configure how to generate the cache key after they set cache=True. But it makes sense to expose the options so that users can customize their cache key generation if they really need it.
>
>For example, if cache=True, then the cache key will be associated with the function signature and parameter values. But users can choose which parameter value to ignore.

I totally agree with this but it might take a while to get this working. How about we create an issue and resolve this in a separate PR?

2023-03-01 07:58 UTC, zhanyuanucb commented on examples/caching/ml_pipeline.py
> +@task(config=dict(cache=True, cache_key_file="hparams"))
@Nilabhra have you implemented this change in this PR?

2023-03-01 08:13 UTC, zhanyuanucb commented on pirlib/cache.py
> +            target_dir = CACHE_DIR + f"/DIR_{cache_key}"
Doesn't quit matter, but just wanna avoid the trouble dealing with `/`, using `os.path.join()` is better here.

2023-03-06 06:59 UTC, Nilabhra commented on examples/caching/ml_pipeline.py
> +@task(config=dict(cache=True, cache_key_file="hparams"))
@zhanyuanucb We haven't made this change in this PR yet. Do you think it's possible to make it right in an upcoming PR and create an issue for this for the moment? Otherwise, this PR will take a while to be completed. At the moment, it's functional albeit incorrectly implemented API wise.

2023-03-06 08:27 UTC, zhanyuanucb commented on examples/caching/ml_pipeline.py
> +@task(config=dict(cache=True, cache_key_file="hparams"))
I think it is good to include this implementation as I saw the timer PR has made a similar change. 
We just need to update the signature of `task` to include cache-related parameters. 
Note that there is no need to change the signature of `TaskDefinition`, we only need to merge the cache flag and the rest into the config like `config["cache"] = cache`.
The idea is to restrict users' freedom in setting this built-in config, but they are still task configs.

2023-03-06 08:31 UTC, zhanyuanucb commented
>> It'll be better if there is a default way to generate the cache key since it is not natural that users must configure how to generate the cache key after they set cache=True. But it makes sense to expose the options so that users can customize their cache key generation if they really need it.

>> For example, if cache=True, then the cache key will be associated with the function signature and parameter values. But users can choose which parameter value to ignore.

> I totally agree with this but it might take a while to get this working. How about we create an issue and resolve this in a separate PR?

@nikhilranjan7 Sure. Let's create an issue to keep track of this after this PR is merged.

2023-03-07 12:07 UTC, Nilabhra commented on examples/caching/ml_pipeline.py
> +@task(config=dict(cache=True, cache_key_file="hparams"))
Alright, we will work on the changes and update the PRs accordingly.

2023-03-16 12:08 UTC, nikhilranjan7 commented on examples/caching/ml_pipeline.py
> +@task(config=dict(cache=True, cache_key_file="hparams"))
@zhanyuanucb this is done, can you help review again

2023-03-21 18:31 UTC, zhanyuanucb approved these changes

2023-03-21 18:31 UTC, merged