Enabling Dynamic Addition of Images for Dockerization
petuum/pirlib pull request #32
Opened 2023-07-25 07:08 UTC by maazmaqsood

**Description:**
This pull request introduces a significant enhancement to our existing dockerization process. Previously, PIRlib was limited to dockerizing only one image at a time, specifically miniconda, which is essential for creating the final dockerized image. With this update, we have empowered users to dynamically add another image of their choice, which will be seamlessly integrated into the final dockerized image.

**Changes Made:**

1. **Dynamic Image Inclusion:** We have modified the dockerization script to allow users to specify an additional image they want to include in the final dockerized build. This enables more flexibility and customization for different use cases and applications.

2. **Example pipelines change:** We have added a new example pipeline, ETL-pipeline and updated multi-backends example. to demonstrate and test the inclusion of dynamic image to the final image.

**Why is this Change Important?**
The ability to add another image dynamically in the dockerization process significantly enhances the versatility and usefulness of PIRlib. It allows users to tailor their dockerized environments to specific requirements, ensuring that diverse applications and dependencies can be effectively encapsulated within the final image.

**Additional Notes:**
I have thoroughly tested the changes, both with the default miniconda image and various supplementary images, ensuring a seamless integration process.

I kindly request a comprehensive review of this pull request to ensure the smooth incorporation of this new feature into PIRlib. Your feedback and suggestions are highly valued, and we are committed to addressing any concerns promptly.

2023-07-26 06:07 UTC, Nilabhra commented
@maazmaqsood Please format the code using black. For black settings, check the `main.yaml` [here](https://github.com/petuum/pirlib/blob/master/.github/workflows/main.yml)

2023-07-26 06:45 UTC, Nilabhra requested changes
@maazmaqsood Added my initial review :). Things are looking good, just needs a few small changes.

2023-07-26 06:45 UTC, Nilabhra commented on examples/etl_pipeline/etl.py
> +# def transform(data:dict) -> pd.DataFrame:
Delete commented function if not needed.

2023-07-26 06:45 UTC, Nilabhra commented on examples/etl_pipeline/etl.py
> +# def load(df:pd.DataFrame)-> None:
Delete commented function if not needed.

2023-07-26 06:45 UTC, Nilabhra commented on pirlib/cli/dockerize.py
> +        'ENV PYSPARK_DRIVER_PYTHON=python3.8'
Why are `PYSPARK_PYTHON` and `PYSPARK_DRIVER` hard coded? Pyspark is only specific to one example. The other examples would not need this ENV var and might even conflict with an user provided base image.

2023-07-26 06:45 UTC, Nilabhra commented on examples/etl_pipeline/etl.py
> +    df = pd.DataFrame(data)
This code block is a bit too dense. See if it can be spaced out using new lines.

2023-07-26 06:45 UTC, Nilabhra commented on pirlib/cli/dockerize.py
> +        "FROM continuumio/miniconda3:latest AS base",
Always pulling the latest image will result in very unstable development experience. It's best if the user can provide the version via a required argument.

2023-07-27 08:09 UTC, maazmaqsood commented on examples/etl_pipeline/etl.py
> +# def transform(data:dict) -> pd.DataFrame:
These were already removed in the later pushes.

2023-07-27 08:09 UTC, maazmaqsood commented on examples/etl_pipeline/etl.py
> +# def load(df:pd.DataFrame)-> None:
These were already removed in the later pushes.

2023-07-27 08:14 UTC, maazmaqsood commented
> @maazmaqsood Added my initial review :). Things are looking good, just needs a few small changes.

Thank you @Nilabhra, code has been updated and pushed. resolving the mentioned issues.

2023-07-27 08:16 UTC, Nilabhra approved these changes

2023-07-27 08:17 UTC, merged