Add tests
petuum/pirlib pull request #7
Opened 2022-07-12 22:58 UTC by zhanyuanucb

Close EPF-416

2022-07-13 02:02 UTC, hunterhector commented
Suggest to have a public issue for tracking purposes

2022-07-20 17:44 UTC, aurickq requested changes

2022-07-20 17:44 UTC, aurickq commented on tests/unit/test_pipeline.py
> +from pirlib.pipeline import pipeline
Can we put unit tests in the same folder as the file being tested, using the name "xxx_test.py"

2022-07-20 17:44 UTC, aurickq commented on tests/unit/test_pipeline.py
> +        return out_path
Does nesting tasks inside a function actually work?

2022-07-20 17:44 UTC, aurickq commented on tests/unit/test_pipeline.py
> +        return out_path
We need tests that actually run the pipeline too

2022-07-20 20:20 UTC, zhanyuanucb commented on tests/unit/test_pipeline.py
> +from pirlib.pipeline import pipeline
You meant

2022-07-20 20:22 UTC, zhanyuanucb commented on tests/unit/test_pipeline.py
> +from pirlib.pipeline import pipeline
You meant something like
```
pirlib/
    pirlib/
    task.py
    task_test.py
    pipeline.py
    pipeline_test.py
```

2022-07-20 20:35 UTC, aurickq commented on tests/unit/test_pipeline.py
> +from pirlib.pipeline import pipeline
Right

2022-07-20 22:13 UTC, zhanyuanucb commented on tests/unit/test_pipeline.py
> +        return out_path
oops... nested task couldn't get the handler while running

2022-07-20 23:01 UTC, zhanyuanucb commented on tests/unit/test_pipeline.py
> +from pirlib.pipeline import pipeline
how about the tests for `example/example.py`? Does it also go into `example`?

2022-07-20 23:04 UTC, zhanyuanucb commented on tests/unit/test_pipeline.py
> +from pirlib.pipeline import pipeline
any reason why here is better to put unit tests and tested code together?

2022-07-21 03:14 UTC, aurickq commented on tests/unit/test_pipeline.py
> +from pirlib.pipeline import pipeline
Mostly down to preference, but this way the unit test file always appears next to the file being tested, and no need to try to maintain a duplicate directory tree under a separate tests folder.

For example.py and other integration tests, can be in a tests folder.

2022-07-21 03:31 UTC, zhanyuanucb commented on tests/unit/test_pipeline.py
> +from pirlib.pipeline import pipeline
updated

2022-07-21 03:40 UTC, aurickq approved these changes

2022-07-21 04:02 UTC, merged